export const FETCH_FLOWS = 'FETCH_FLOWS';
export const RECEIVE_FLOWS = 'RECEIVE_FLOWS';

export const GET_MODULES = 'RECEIVE_MODULES';

export const SAVED_FLOW = 'SAVED_FLOW';
export const UPDATE_NODE_CONN = 'UPDATE_NODE_CONN';
export const UPDATE_NODE_OPT = 'UPDATE_NODE_OPT';
export const UPDATE_NODE_OPTS = 'UPDATE_NODE_OPTS';
export const UPDATE_NODE_OUTPUT = 'UPDATE_NODE_OUTPUT';

export const UPDATE_FLOW_DIAGRAM = 'UPDATE_FLOW_DIAGRAM';
export const SET_TAB = 'SET_TAB';
export const SELECT_NODE = 'SELECT_NODE';
export const EDIT_FLOW = 'EDIT_FLOW';

